version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
      - "6006:6006"
    volumes:
      - ./conteudo_ficticio:/app/conteudo_ficticio
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - DOCKER_CONTAINER=true
    depends_on:
      - chromadb
  
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma

volumes:
  chroma_data: